### ISSUE TITLE
use of file aux.triples

### ISSUE THREAD

**Issue by Surkea** [kingsaint/InductiveExplainableLinkPrediction#3]
dear developer：
   Im working on this code, but i can't figure out the use of file aux.tripes, could you pls explain it generally, thx

**Comment by kingsaint** [comment]
The `aux.triples` are used only during testing (inference), [Please check this line](https://github.com/kingsaint/InductiveExplainableLinkPrediction/blob/master/src/rl/graph_search/pn.py#L131 )
Every subject entity in the `test.triples` file is present either as a subject or as an object entity of the triples in `aux.triples` file. Therefore, `aux.triples` file serve as the local neighborhood of the unseen entities during testing. Hope this helps.

**Comment by Surkea** [comment]
It helps a lot, thx!!
